from typing import Protocol, Optional
from sqlalchemy.ext.asyncio import AsyncSession
from app.domain.entities import Line, Conductor, StudyCase, Calculation, SeasonalPercentiles
from app.domain.types import Season


class ILinesRepository(Protocol):
    async def get_all(self, db: AsyncSession, owner_id: str) -> list[Line]: ...
    async def get_by_id(self, db: AsyncSession, line_id: str, owner_id: str) -> Line: ...
    async def exists(self, db: AsyncSession, line_id: str, owner_id: str) -> bool: ...
    async def create(self, db: AsyncSession, owner_id: str, entity: Line) -> Line: ...
    async def update(self, db: AsyncSession, line_id: str, owner_id: str, entity: Line) -> Line: ...
    async def delete(self, db: AsyncSession, line_id: str, owner_id: str) -> bool: ...


class IConductorsRepository(Protocol):
    async def get_all(self, db: AsyncSession, owner_id: str) -> list[Conductor]: ...
    async def get_by_id(self, db: AsyncSession, conductor_id: str, owner_id: str) -> Conductor: ...
    async def exists(self, db: AsyncSession, conductor_id: str, owner_id: str) -> bool: ...
    async def create(self, db: AsyncSession, owner_id: str, entity: Conductor) -> Conductor: ...
    async def update(self, db: AsyncSession, conductor_id: str, owner_id: str, entity: Conductor) -> Conductor: ...
    async def delete(self, db: AsyncSession, conductor_id: str, owner_id: str) -> bool: ...


class IStudyCasesRepository(Protocol):
    async def get_all(self, db: AsyncSession, owner_id: str) -> list[StudyCase]: ...
    async def get_by_id(self, db: AsyncSession, case_id: str, owner_id: str) -> StudyCase: ...
    async def exists(self, db: AsyncSession, case_id: str, owner_id: str) -> bool: ...
    async def create(self, db: AsyncSession, owner_id: str, entity: StudyCase) -> StudyCase: ...
    async def update(self, db: AsyncSession, case_id: str, owner_id: str, entity: StudyCase) -> StudyCase: ...
    async def delete(self, db: AsyncSession, case_id: str, owner_id: str) -> bool: ...


class ICalculationsRepository(Protocol):
    async def create(self, db: AsyncSession, entity: Calculation) -> Calculation: ...
    async def get_by_id(self, db: AsyncSession, calc_id: str, user_id: str | None = None) -> Calculation: ...
    async def get_by_study_case(self, db: AsyncSession, case_id: str, user_id: str) -> list[Calculation]: ...
    async def delete(self, db: AsyncSession, calc_id: str, user_id: str | None = None) -> bool: ...


class IElevationRepository(Protocol):
    async def get_elevation(self, db: AsyncSession, lat: float, lon: float) -> float | None: ...
    async def create_elevation(self, db: AsyncSession, lat: float, lon: float, elevation_m: float) -> None: ...


class IClimateRepository(Protocol):
    async def get_climate(
        self, db: AsyncSession, lat: float, lon: float, source: str
    ) -> dict[Season, SeasonalPercentiles] | None: ...
    async def create_climate(
        self, db: AsyncSession, percentiles: dict[Season, SeasonalPercentiles]
    ) -> None: ...


class IUsersRepository(Protocol):
    async def get_by_id(self, db: AsyncSession, user_id: str): ...
    async def get_by_username(self, db: AsyncSession, username: str): ...
    async def create(self, db: AsyncSession, username: str, hashed_password: str): ...
    async def exists_by_username(self, db: AsyncSession, username: str) -> bool: ...